apiVersion: batch/v1
kind: Job
metadata:
  name: cifar10-single-job-3
spec:
  parallelism: 1
  template:
    metadata:
      name: cifar10-single-job
      labels:
        app: cifar10-single-job
    spec:
      restartPolicy: Never
      containers:
       - name: pytorch
         image: nvcr.io/nvidia/pytorch:18.11-py3
         workingDir: /cifar10-training
         env:
         - name: JOB_ID
           value: "3"
         command: ["bash"]
         args: ["-c","python cifar10_train.py"]
         volumeMounts:
         - name: cifar10-training
           mountPath: /cifar10-training
         - name: cifar10-dataset
           mountPath: /mnt/share
         resources:
           limits:
             nvidia.com/gpu: 2
      volumes:
      - name: cifar10-training
        gitRepo:
          repository: https://github.com/kubertest/kubernetes-hyperparam-exp.git
          revision: master
          directory: .
      - name: cifar10-dataset
        nfs:
          server: 192.168.88.251
          path: /home/rakshith/test1/kubernetes-hyperparam-exp/datasets
      
